import React from "react";
import navigationData from "@/src/utils/navigationData";
import { Navigation, Footer } from "..";
import Head from "next/head";

export default function Layout({ title, children, active = "" }) {
  return (
    <>
      <Head>
        <title>{`Sate Taichan : ${title}`}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imgs/sate-erik-bg.png" />
      </Head>
      <Navigation navLink={navigationData} active={active} />
      <main>{children}</main>
      <Footer />
    </>
  );
}
